"""
Problem 2.

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

https:projecteuler.net/problem=2
"""

from itertools import takewhile


def fibs():
    """Generator for Fibonacci numbers."""
    i, j = 1, 2
    while True:
        yield i
        i, j = j, i+j


# Print the sum of even Fibonacci numbers less than four million.
print(sum([i for i in takewhile(lambda i: i < 4000000, fibs()) if i % 2 == 0]))
